name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}       # example: 3.93.11.181
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}     # your PEM private key
          script: |
            cd ~/nodeapp || git clone https://github.com/jas-fullstack/nodeapp.git ~/nodeapp
            cd ~/nodeapp
            git pull origin main
            npm install
            pm2 restart myapp || pm2 start app.js --name myapp
